### PR TITLE
Revert "Add weapon and debug shooting. Work on applying damage."

### PR DESCRIPTION
**Pull request by VladPodilnyk**
Reverts VladPodilnyk/WarriorsArena#1

### CODE REVIEW

**Comment by VladPodilnyk** [comment]
Something wrong with your last commit. I think it's due to different platforms that we use to develop into.
Try to not touch an engine configuration files, I mean don't add them into the commit.

**Comment by VladPodilnyk** [comment]
Another issue that I've found,  is that you didn't complete the second section. I could not find smoke trailing effect and crosshair. Also, did you add a grenade launcher?

**Comment by SteadyCoder** [comment]
There is troubles happening always when I am trying to open project with 4.17.2 version. I can't open it throws error when building it.

**Comment by SteadyCoder** [comment]
screen shot 2018-10-17 at 1 02 12 am
this is what happens when I am trying to launch.

**Comment by SteadyCoder** [comment]
screen shot 2018-10-17 at 1 02 12 am
This happens after build completed. Error is that not found some methods in binaries.

**Comment by VladPodilnyk** [comment]
So you copied the repo and tried to launch the projects and the shit happened? Could you reproduce it on a Windows machine? Will it take too much time?

**Comment by VladPodilnyk** [comment]
Also, have you googled it?

**Comment by VladPodilnyk** [comment]
Okay, I found something interesting. First of all, you are not the only one who has faced this issue. There some difficulties when a project,  which was built in Windows, is compiled in OSX.
I hope the following links help you to handle the situation or at least give you a hint about what happened:

https://forums.unrealengine.com/development-discussion/c-gameplay-programming/39705-compiling-windows-project-on-osx-the-following-modules-are-missing-or-built-with-a-different

https://answers.unrealengine.com/questions/220724/problems-building-windows-project-on-osx.html

https://docs.unrealengine.com/en-us/Programming/Development/BuildingUnrealEngine

**Comment by VladPodilnyk** [comment]
Yeah, pls notify me ASAP about your progress. We should handle that quickly and move on.

**Pull request closed without merging**
